#!/usr/bin/env bash

CMD='-cs -i4 -mUDP -l50'

R=(10 50 100 200 400)
N=(10 50 100 200)

cd $(dirname $0)

for r in ${R[@]}
do
    for n in ${N[@]}
    do
        [ $n -gt $r ] && continue
        name="r=${r}_n=${n}"
        ./test $name REPLICAS=$r CMD="$CMD -n$n"
    done
done

